B2CWebsite/Controllers/CheckOutController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using B2CWebsite.Extension;
using B2CWebsite.Models;
using B2CWebsite.ModelViews;
using Microsoft.AspNetCore.Mvc;

namespace B2CWebsite.Controllers
{
    public class CheckOutController : Controller
    {
        private readonly DrugStoreContext _context;
        public INotyfService _notyfService { get; }
        public CheckOutController(DrugStoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        public List<CartItem> ShoppingCart
        {
            get
            {
                var cart = HttpContext.Session.Get<List<CartItem>>("ShoppingCart");
                if (cart == default(List<CartItem>))
                {
                    cart = new List<CartItem>();
                }
                return cart;
            }
        }
        [Route("checkout.html", Name = "Checkout")]
        public IActionResult Index(string returnUrl = null)     
        {
            return View();
        }
    }
}

B2CWebsite/Controllers/ShoppingCartController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using B2CWebsite.Extension;
using B2CWebsite.Models;
using B2CWebsite.ModelViews;
using Microsoft.AspNetCore.Mvc;

namespace B2CWebsite.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly DrugStoreContext _context;
        public INotyfService _notyfService { get; }
        public ShoppingCartController(DrugStoreContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        public List<CartItem> ShoppingCart
        {
            get
            {
                var sc = HttpContext.Session.Get<List<CartItem>>("ShoppingCart");
                if (sc == default(List<CartItem>))
                {
                    sc = new List<CartItem>();
                }
                return sc;
            }
        }
        [HttpPost]
        [Route("api/cart/add")]
        public IActionResult AddToCart(int SID, int? amount)
        {
            List<CartItem> cart = ShoppingCart;

            try
            {
                CartItem item = cart.SingleOrDefault(p => p.supplement.Sid == SID);
                if (item != null) 
                {
                    item.amount = item.amount + amount.Value;
                    //save session
                    HttpContext.Session.Set<List<CartItem>>("ShoppingCart", cart);
                }
                else
                {
                    Supplement hh = _context.Supplements.SingleOrDefault(p => p.Sid == SID);
                    item = new CartItem
                    {
                        amount = amount.HasValue ? amount.Value : 1,
                        supplement = hh
                    };
                    cart.Add(item);
                }

                //save
                HttpContext.Session.Set<List<CartItem>>("ShoppingCart", cart);
                _notyfService.Success("Added product successfully to the cart");
                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }
        [HttpPost]
        [Route("api/cart/update")]
        public IActionResult UpdateCart(int SID, int? amount)
        {

            var cart1 = HttpContext.Session.Get<List<CartItem>>("ShoppingCart");
            try
            {
                if (cart1 != null)
                {
                    CartItem item = cart1.SingleOrDefault(p => p.supplement.Sid == SID);
                    if (item != null && amount.HasValue)
                    {
                        item.amount = amount.Value;
                    }
                    //Luu lai session
                    HttpContext.Session.Set<List<CartItem>>("ShoppingCart", cart1);
                }
                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }
        [HttpPost]
        [Route("api/cart/remove")]
        public ActionResult Remove(int SID)
        {

            try
            {
                List<CartItem>  cart = ShoppingCart;
                CartItem item = cart.SingleOrDefault(p => p.supplement.Sid == SID);
                if (item != null)
                {
                    cart.Remove(item);
                }
                //luu lai session
                HttpContext.Session.Set<List<CartItem>>("ShoppingCart", cart);
                return Json(new { success = true });
            }
            catch
            {
                return Json(new { success = false });
            }
        }
        [Route("cart.html", Name = "Cart")]
        public IActionResult Index()
        {
            return View(ShoppingCart);
        }
    }
}

B2CWebsite/Views/ShoppingCart/Index.cshtml
@model List<B2CWebsite.ModelViews.CartItem>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" asp-controller="Home" asp-action="Index">Home</a>
                <a class="breadcrumb-item text-dark" asp-asp-controller="Supplement" asp-action="Index">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->
<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    <tr>
                        <td class="align-middle"><img src="~/img/mamori.png" alt=" style="width: 50px;"> Mamori Nattokinase (Box of 60 tablets)</td>
                        <td class="align-middle">638.000 VND</td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-minus">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                </div>
                                <input type="text" class="form-control form-control-sm bg-secondary border-0 text-center" value="1">
                                <div class="input-group-btn">
                                    <button class="btn btn-sm btn-primary btn-plus">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                </div>
                            </div>
                        </td>
                        <td class="align-middle">638.000</td>
                        <td class="align-middle"><button class="btn btn-sm btn-danger"><i class="fa fa-times"></i></button></td>
                    </tr>

                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>638.000 VND</h6>
                    </div>
                </div>

                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>638.000 VND</h5>
                    </div>
                    <a class="btn btn-block btn-primary font-weight-bold my-3 py-3" asp-controller="CheckOut" asp-action="Index">Proceed To Checkout</a>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->